CREATE SCHEMA IF NOT EXISTS tickets;

CREATE TABLE IF NOT EXISTS tickets.tickets (
                                               id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               title        TEXT        NOT NULL,
                                               description  TEXT        NOT NULL,
                                               status       TEXT        NOT NULL DEFAULT 'OPEN',
                                               owner_id     INTEGER     NOT NULL,
                                               assignee_id  INTEGER,
                                               created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
                                               updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);