CREATE TABLE IF NOT EXISTS tickets.attachments_meta (
                                                   id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                   ticket_id     INTEGER     NOT NULL REFERENCES tickets.tickets(id) ON DELETE CASCADE,
                                                   blob_path     VARCHAR(512) NOT NULL,
                                                   original_name VARCHAR(255) NOT NULL,
                                                   content_type  VARCHAR(100) NOT NULL,
                                                   size_bytes    BIGINT       NOT NULL CHECK (size_bytes >= 0),
                                                   scan_status   VARCHAR(16)  NOT NULL CHECK (scan_status IN ('PENDING','CLEAN','QUARANTINED')),
                                                   created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);